global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'test_app'
    metrics_path: /metrics
    static_configs:
      - targets:
         - 'gateway:5000'
         - 'catalog:5001'
         - 'cart:5002'
         - 'payment:5003'
