global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'test_app'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:5000'
          - 'host.docker.internal:5001'
          - 'host.docker.internal:5002'
          - 'host.docker.internal:5003'
